// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct TunnelRouteV4: Hashable {
  var destinationAddress: String
  var subnetMask: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TunnelRouteV4? {
    let destinationAddress = pigeonVar_list[0] as! String
    let subnetMask = pigeonVar_list[1] as! String

    return TunnelRouteV4(
      destinationAddress: destinationAddress,
      subnetMask: subnetMask
    )
  }
  func toList() -> [Any?] {
    return [
      destinationAddress,
      subnetMask,
    ]
  }
  static func == (lhs: TunnelRouteV4, rhs: TunnelRouteV4) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TunnelRouteV6: Hashable {
  var destinationAddress: String
  var networkPrefixLength: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TunnelRouteV6? {
    let destinationAddress = pigeonVar_list[0] as! String
    let networkPrefixLength = pigeonVar_list[1] as! Int64

    return TunnelRouteV6(
      destinationAddress: destinationAddress,
      networkPrefixLength: networkPrefixLength
    )
  }
  func toList() -> [Any?] {
    return [
      destinationAddress,
      networkPrefixLength,
    ]
  }
  static func == (lhs: TunnelRouteV6, rhs: TunnelRouteV6) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TunnelProfile: Hashable {
  var mtu: Int64
  var tun46Setting: Int64
  var defaultNicSupport6: Bool
  var dnsServers4: [String]
  var dnsServers6: [String]
  var ipv4Addresses: [String]
  var ipv4SubnetMasks: [String]
  var ipv4IncludedRoutes: [TunnelRouteV4]
  var ipv4ExcludedRoutes: [TunnelRouteV4]
  var ipv6Addresses: [String]
  var ipv6NetworkPrefixLengths: [Int64]
  var ipv6IncludedRoutes: [TunnelRouteV6]
  var ipv6ExcludedRoutes: [TunnelRouteV6]
  var configPath: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TunnelProfile? {
    let mtu = pigeonVar_list[0] as! Int64
    let tun46Setting = pigeonVar_list[1] as! Int64
    let defaultNicSupport6 = pigeonVar_list[2] as! Bool
    let dnsServers4 = pigeonVar_list[3] as! [String]
    let dnsServers6 = pigeonVar_list[4] as! [String]
    let ipv4Addresses = pigeonVar_list[5] as! [String]
    let ipv4SubnetMasks = pigeonVar_list[6] as! [String]
    let ipv4IncludedRoutes = pigeonVar_list[7] as! [TunnelRouteV4]
    let ipv4ExcludedRoutes = pigeonVar_list[8] as! [TunnelRouteV4]
    let ipv6Addresses = pigeonVar_list[9] as! [String]
    let ipv6NetworkPrefixLengths = pigeonVar_list[10] as! [Int64]
    let ipv6IncludedRoutes = pigeonVar_list[11] as! [TunnelRouteV6]
    let ipv6ExcludedRoutes = pigeonVar_list[12] as! [TunnelRouteV6]
    let configPath = pigeonVar_list[13] as! String

    return TunnelProfile(
      mtu: mtu,
      tun46Setting: tun46Setting,
      defaultNicSupport6: defaultNicSupport6,
      dnsServers4: dnsServers4,
      dnsServers6: dnsServers6,
      ipv4Addresses: ipv4Addresses,
      ipv4SubnetMasks: ipv4SubnetMasks,
      ipv4IncludedRoutes: ipv4IncludedRoutes,
      ipv4ExcludedRoutes: ipv4ExcludedRoutes,
      ipv6Addresses: ipv6Addresses,
      ipv6NetworkPrefixLengths: ipv6NetworkPrefixLengths,
      ipv6IncludedRoutes: ipv6IncludedRoutes,
      ipv6ExcludedRoutes: ipv6ExcludedRoutes,
      configPath: configPath
    )
  }
  func toList() -> [Any?] {
    return [
      mtu,
      tun46Setting,
      defaultNicSupport6,
      dnsServers4,
      dnsServers6,
      ipv4Addresses,
      ipv4SubnetMasks,
      ipv4IncludedRoutes,
      ipv4ExcludedRoutes,
      ipv6Addresses,
      ipv6NetworkPrefixLengths,
      ipv6IncludedRoutes,
      ipv6ExcludedRoutes,
      configPath,
    ]
  }
  static func == (lhs: TunnelProfile, rhs: TunnelProfile) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TunnelStatus: Hashable {
  var state: String
  var lastError: String? = nil
  var utunInterfaces: [String]
  var startedAt: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TunnelStatus? {
    let state = pigeonVar_list[0] as! String
    let lastError: String? = nilOrValue(pigeonVar_list[1])
    let utunInterfaces = pigeonVar_list[2] as! [String]
    let startedAt: Int64? = nilOrValue(pigeonVar_list[3])

    return TunnelStatus(
      state: state,
      lastError: lastError,
      utunInterfaces: utunInterfaces,
      startedAt: startedAt
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      lastError,
      utunInterfaces,
      startedAt,
    ]
  }
  static func == (lhs: TunnelStatus, rhs: TunnelStatus) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return TunnelRouteV4.fromList(self.readValue() as! [Any?])
    case 130:
      return TunnelRouteV6.fromList(self.readValue() as! [Any?])
    case 131:
      return TunnelProfile.fromList(self.readValue() as! [Any?])
    case 132:
      return TunnelStatus.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TunnelRouteV4 {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? TunnelRouteV6 {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? TunnelProfile {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? TunnelStatus {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DarwinHostApi {
  func appGroupPath() throws -> String
  func startXApiServer(config: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func redirectStdErr(path: String, completion: @escaping (Result<Void, Error>) -> Void)
  func generateTls() throws -> FlutterStandardTypedData
  func setupShutdownNotification() throws
  func savePacketTunnelProfile(profile: TunnelProfile) throws -> String
  func startPacketTunnel(completion: @escaping (Result<Void, Error>) -> Void)
  func stopPacketTunnel(completion: @escaping (Result<Void, Error>) -> Void)
  func getPacketTunnelStatus() throws -> TunnelStatus
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DarwinHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `DarwinHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DarwinHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let appGroupPathChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xstream.DarwinHostApi.appGroupPath\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      appGroupPathChannel.setMessageHandler { _, reply in
        do {
          let result = try api.appGroupPath()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      appGroupPathChannel.setMessageHandler(nil)
    }
    let startXApiServerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xstream.DarwinHostApi.startXApiServer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startXApiServerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! FlutterStandardTypedData
        api.startXApiServer(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startXApiServerChannel.setMessageHandler(nil)
    }
    let redirectStdErrChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xstream.DarwinHostApi.redirectStdErr\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      redirectStdErrChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.redirectStdErr(path: pathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      redirectStdErrChannel.setMessageHandler(nil)
    }
    let generateTlsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xstream.DarwinHostApi.generateTls\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateTlsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.generateTls()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      generateTlsChannel.setMessageHandler(nil)
    }
    let setupShutdownNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xstream.DarwinHostApi.setupShutdownNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setupShutdownNotificationChannel.setMessageHandler { _, reply in
        do {
          try api.setupShutdownNotification()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setupShutdownNotificationChannel.setMessageHandler(nil)
    }
    let savePacketTunnelProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xstream.DarwinHostApi.savePacketTunnelProfile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      savePacketTunnelProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let profileArg = args[0] as! TunnelProfile
        do {
          let result = try api.savePacketTunnelProfile(profile: profileArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      savePacketTunnelProfileChannel.setMessageHandler(nil)
    }
    let startPacketTunnelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xstream.DarwinHostApi.startPacketTunnel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startPacketTunnelChannel.setMessageHandler { _, reply in
        api.startPacketTunnel { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startPacketTunnelChannel.setMessageHandler(nil)
    }
    let stopPacketTunnelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xstream.DarwinHostApi.stopPacketTunnel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopPacketTunnelChannel.setMessageHandler { _, reply in
        api.stopPacketTunnel { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopPacketTunnelChannel.setMessageHandler(nil)
    }
    let getPacketTunnelStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xstream.DarwinHostApi.getPacketTunnelStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPacketTunnelStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPacketTunnelStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPacketTunnelStatusChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DarwinFlutterApiProtocol {
  func onSystemWillShutdown(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSystemWillRestart(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSystemWillSleep(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPacketTunnelStateChanged(status statusArg: TunnelStatus, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPacketTunnelError(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class DarwinFlutterApi: DarwinFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onSystemWillShutdown(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.xstream.DarwinFlutterApi.onSystemWillShutdown\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onSystemWillRestart(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.xstream.DarwinFlutterApi.onSystemWillRestart\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onSystemWillSleep(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.xstream.DarwinFlutterApi.onSystemWillSleep\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPacketTunnelStateChanged(status statusArg: TunnelStatus, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.xstream.DarwinFlutterApi.onPacketTunnelStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPacketTunnelError(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.xstream.DarwinFlutterApi.onPacketTunnelError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
