// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class TunnelRouteV4 {
  TunnelRouteV4({
    required this.destinationAddress,
    required this.subnetMask,
  });

  String destinationAddress;

  String subnetMask;

  List<Object?> _toList() {
    return <Object?>[
      destinationAddress,
      subnetMask,
    ];
  }

  Object encode() {
    return _toList();  }

  static TunnelRouteV4 decode(Object result) {
    result as List<Object?>;
    return TunnelRouteV4(
      destinationAddress: result[0]! as String,
      subnetMask: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TunnelRouteV4 || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class TunnelRouteV6 {
  TunnelRouteV6({
    required this.destinationAddress,
    required this.networkPrefixLength,
  });

  String destinationAddress;

  int networkPrefixLength;

  List<Object?> _toList() {
    return <Object?>[
      destinationAddress,
      networkPrefixLength,
    ];
  }

  Object encode() {
    return _toList();  }

  static TunnelRouteV6 decode(Object result) {
    result as List<Object?>;
    return TunnelRouteV6(
      destinationAddress: result[0]! as String,
      networkPrefixLength: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TunnelRouteV6 || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class TunnelProfile {
  TunnelProfile({
    required this.mtu,
    required this.tun46Setting,
    required this.defaultNicSupport6,
    required this.dnsServers4,
    required this.dnsServers6,
    required this.ipv4Addresses,
    required this.ipv4SubnetMasks,
    required this.ipv4IncludedRoutes,
    required this.ipv4ExcludedRoutes,
    required this.ipv6Addresses,
    required this.ipv6NetworkPrefixLengths,
    required this.ipv6IncludedRoutes,
    required this.ipv6ExcludedRoutes,
    required this.configPath,
  });

  int mtu;

  int tun46Setting;

  bool defaultNicSupport6;

  List<String> dnsServers4;

  List<String> dnsServers6;

  List<String> ipv4Addresses;

  List<String> ipv4SubnetMasks;

  List<TunnelRouteV4> ipv4IncludedRoutes;

  List<TunnelRouteV4> ipv4ExcludedRoutes;

  List<String> ipv6Addresses;

  List<int> ipv6NetworkPrefixLengths;

  List<TunnelRouteV6> ipv6IncludedRoutes;

  List<TunnelRouteV6> ipv6ExcludedRoutes;

  String configPath;

  List<Object?> _toList() {
    return <Object?>[
      mtu,
      tun46Setting,
      defaultNicSupport6,
      dnsServers4,
      dnsServers6,
      ipv4Addresses,
      ipv4SubnetMasks,
      ipv4IncludedRoutes,
      ipv4ExcludedRoutes,
      ipv6Addresses,
      ipv6NetworkPrefixLengths,
      ipv6IncludedRoutes,
      ipv6ExcludedRoutes,
      configPath,
    ];
  }

  Object encode() {
    return _toList();  }

  static TunnelProfile decode(Object result) {
    result as List<Object?>;
    return TunnelProfile(
      mtu: result[0]! as int,
      tun46Setting: result[1]! as int,
      defaultNicSupport6: result[2]! as bool,
      dnsServers4: (result[3] as List<Object?>?)!.cast<String>(),
      dnsServers6: (result[4] as List<Object?>?)!.cast<String>(),
      ipv4Addresses: (result[5] as List<Object?>?)!.cast<String>(),
      ipv4SubnetMasks: (result[6] as List<Object?>?)!.cast<String>(),
      ipv4IncludedRoutes: (result[7] as List<Object?>?)!.cast<TunnelRouteV4>(),
      ipv4ExcludedRoutes: (result[8] as List<Object?>?)!.cast<TunnelRouteV4>(),
      ipv6Addresses: (result[9] as List<Object?>?)!.cast<String>(),
      ipv6NetworkPrefixLengths: (result[10] as List<Object?>?)!.cast<int>(),
      ipv6IncludedRoutes: (result[11] as List<Object?>?)!.cast<TunnelRouteV6>(),
      ipv6ExcludedRoutes: (result[12] as List<Object?>?)!.cast<TunnelRouteV6>(),
      configPath: result[13]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TunnelProfile || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class TunnelStatus {
  TunnelStatus({
    required this.state,
    this.lastError,
    required this.utunInterfaces,
    this.startedAt,
  });

  String state;

  String? lastError;

  List<String> utunInterfaces;

  int? startedAt;

  List<Object?> _toList() {
    return <Object?>[
      state,
      lastError,
      utunInterfaces,
      startedAt,
    ];
  }

  Object encode() {
    return _toList();  }

  static TunnelStatus decode(Object result) {
    result as List<Object?>;
    return TunnelStatus(
      state: result[0]! as String,
      lastError: result[1] as String?,
      utunInterfaces: (result[2] as List<Object?>?)!.cast<String>(),
      startedAt: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TunnelStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TunnelRouteV4) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is TunnelRouteV6) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is TunnelProfile) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is TunnelStatus) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return TunnelRouteV4.decode(readValue(buffer)!);
      case 130: 
        return TunnelRouteV6.decode(readValue(buffer)!);
      case 131: 
        return TunnelProfile.decode(readValue(buffer)!);
      case 132: 
        return TunnelStatus.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class DarwinHostApi {
  /// Constructor for [DarwinHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DarwinHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String> appGroupPath() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.xstream.DarwinHostApi.appGroupPath$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> startXApiServer(Uint8List config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.xstream.DarwinHostApi.startXApiServer$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> redirectStdErr(String path) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.xstream.DarwinHostApi.redirectStdErr$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<Uint8List> generateTls() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.xstream.DarwinHostApi.generateTls$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Uint8List?)!;
    }
  }

  Future<void> setupShutdownNotification() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.xstream.DarwinHostApi.setupShutdownNotification$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> savePacketTunnelProfile(TunnelProfile profile) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.xstream.DarwinHostApi.savePacketTunnelProfile$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[profile]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> startPacketTunnel() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.xstream.DarwinHostApi.startPacketTunnel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopPacketTunnel() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.xstream.DarwinHostApi.stopPacketTunnel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<TunnelStatus> getPacketTunnelStatus() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.xstream.DarwinHostApi.getPacketTunnelStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as TunnelStatus?)!;
    }
  }
}

abstract class DarwinFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onSystemWillShutdown();

  void onSystemWillRestart();

  void onSystemWillSleep();

  void onPacketTunnelStateChanged(TunnelStatus status);

  void onPacketTunnelError(String code, String message);

  static void setUp(DarwinFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.xstream.DarwinFlutterApi.onSystemWillShutdown$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onSystemWillShutdown();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.xstream.DarwinFlutterApi.onSystemWillRestart$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onSystemWillRestart();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.xstream.DarwinFlutterApi.onSystemWillSleep$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onSystemWillSleep();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.xstream.DarwinFlutterApi.onPacketTunnelStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.xstream.DarwinFlutterApi.onPacketTunnelStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TunnelStatus? arg_status = (args[0] as TunnelStatus?);
          assert(arg_status != null,
              'Argument for dev.flutter.pigeon.xstream.DarwinFlutterApi.onPacketTunnelStateChanged was null, expected non-null TunnelStatus.');
          try {
            api.onPacketTunnelStateChanged(arg_status!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.xstream.DarwinFlutterApi.onPacketTunnelError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.xstream.DarwinFlutterApi.onPacketTunnelError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_code = (args[0] as String?);
          assert(arg_code != null,
              'Argument for dev.flutter.pigeon.xstream.DarwinFlutterApi.onPacketTunnelError was null, expected non-null String.');
          final String? arg_message = (args[1] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.xstream.DarwinFlutterApi.onPacketTunnelError was null, expected non-null String.');
          try {
            api.onPacketTunnelError(arg_code!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
